 pipeline {
    agent any
    environment{
        VERSION = "${env.BUILD_ID}"
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
     stage('docker image') {
      steps {
       sh 'docker build . -t yannickeboo:app1-$VERSION -f account-service/Dockerfile'
    
       sh 'docker push yannickeboo:app1-$VERSION'
         
      }
     }
    }
}
