 pipeline {
    agent any
    environment{
        VERSION = "${env.BUILD_ID}"
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
       stage('docker image'){
        steps{
         dir('/account-service/'){
            sh 'cd /account-service/ | docker build -t yannickeboo:${VERSION} .'
            sh 'docker login -u yannickeboo -p $docker_yann'
                              
         }           
        
             }
     }
    }
}
